LIBS=-ldl -lglfw -lGL
INC=-Ilibraries/GLM -Ilibraries/GLAD_V4.5/include -Ilibraries/GLFW_x32/inlcude

Booleans: Main.cpp
	g++ libraries/GLAD_V4.5/src/glad.c Header.h ImageBuffer.h Objects.h ImageBuffer.cpp Lighting.cpp Utilities.cpp Main.cpp -fopenmp -w -o Booleans $(LIBS) $(INC)


